spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-server:8888
  discovery:
    enabled: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery-server:8761/eureka/
      register-with-eureka: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: default-path
          uri: lb://resource-catalog-service
          predicates:
            - Path=/api/resource-catalog/**

security:
  oauth2:
    client:
      registration:
        keycloak:
          client-id: gateway-client
          client-secret: gateway-secret
          authorization-grant-type: authorization_code
          redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
          scope:
            - openid
            - profile
            - email
      provider:
        keycloak:
          issuer-uri: http://keycloak:8080/realms/master

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
