server:
  port: 8761

spring:
  application:
    name: discovery-server

  datasource:
    url: jdbc:postgresql://postgres:5432/resource_allocation
    username: app
    password: app-pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
