spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: resource-catalog
          uri: lb://resource-catalog-service
          predicates:
            - Path=/api/resource-catalog/**
        - id: booking
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: permissions
          uri: lb://permission-service
          predicates:
            - Path=/api/permissions/**

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

authorization:
  openid:
    issuer-uri: http://keycloak:8080/realms/master
